# Generated by Django 6.0.4 on 2026-05-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_add_race_email_to_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="immunization",
            name="encounter_id",
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
