# Generated by Django 6.0.4 on 2026-05-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_make_immunization_encounter_id_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="philsys_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="pwd_expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="pwd_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="pwd_issuing_lgu",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["philsys_id"], name="patient_philsys_23a69f_idx"
            ),
        ),
    ]
