# Generated by Django 6.0.4 on 2026-05-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_phcore_alignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="allergyintolerance",
            name="reaction_manifestation_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
