# Generated by Django 6.0.4 on 2026-05-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="value_quantity_unit",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
