# Generated by Django 6.0.4 on 2026-05-04 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                ("appointment_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cancellation_reason_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "cancellation_reason_display",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "service_category_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "service_category_display",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "service_type_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "service_type_display",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "specialty_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "specialty_display",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "appointment_type_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "appointment_type_display",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reason_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reason_reference_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("priority", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("start", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("created_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "minutes_duration",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "slot_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("patient_id", models.BigIntegerField(db_index=True)),
                (
                    "practitioner_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "location_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "patient_participation_status",
                    models.CharField(
                        blank=True,
                        help_text="accepted | declined | tentative | needs-action",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "practitioner_participation_status",
                    models.CharField(
                        blank=True,
                        help_text="accepted | declined | tentative | needs-action",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "based_on_service_request_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "resulting_encounter_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("patient_instruction", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "appointment",
                "indexes": [
                    models.Index(
                        fields=["patient_id", "start"],
                        name="appointment_patient_a35731_idx",
                    ),
                    models.Index(
                        fields=["practitioner_id", "start"],
                        name="appointment_practit_d3d076_idx",
                    ),
                    models.Index(
                        fields=["status", "start"], name="appointment_status_9ed647_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                ("schedule_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "actor_practitioner_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "actor_location_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "actor_organization_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "service_type_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "service_type_display",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "specialty_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "specialty_display",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("planning_horizon_start", models.DateTimeField(blank=True, null=True)),
                ("planning_horizon_end", models.DateTimeField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "appointment_schedule",
                "indexes": [
                    models.Index(
                        fields=["actor_practitioner_id"],
                        name="appointment_actor_p_bf9fc2_idx",
                    ),
                    models.Index(
                        fields=["actor_location_id"],
                        name="appointment_actor_l_b1f71a_idx",
                    ),
                    models.Index(
                        fields=["planning_horizon_start", "planning_horizon_end"],
                        name="appointment_plannin_f267de_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                (
                    "service_request_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "intent",
                    models.CharField(
                        blank=True,
                        help_text="proposal | plan | directive | order | ...",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("priority", models.CharField(blank=True, max_length=100, null=True)),
                ("code", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "code_system",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "code_display",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("subject_id", models.BigIntegerField(db_index=True)),
                (
                    "encounter_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "requester_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "performer_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "reason_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("occurrence_datetime", models.DateTimeField(blank=True, null=True)),
                ("authored_on", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "service_request",
                "indexes": [
                    models.Index(
                        fields=["subject_id"], name="service_req_subject_722116_idx"
                    ),
                    models.Index(
                        fields=["status"], name="service_req_status_a47ea4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Slot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                ("slot_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "service_type_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "service_type_display",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "specialty_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "specialty_display",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "appointment_type_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "appointment_type_display",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("start", models.DateTimeField(db_index=True)),
                ("end", models.DateTimeField()),
                ("overbooked", models.BooleanField(default=False)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        db_column="schedule_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="admission.schedule",
                    ),
                ),
            ],
            options={
                "db_table": "appointment_slot",
                "indexes": [
                    models.Index(
                        fields=["schedule", "start"],
                        name="appointment_schedul_5c7f9f_idx",
                    ),
                    models.Index(
                        fields=["status", "start"], name="appointment_status_a191f7_idx"
                    ),
                ],
            },
        ),
    ]
