# Generated by Django 6.0.4 on 2026-05-24 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0002_add_appointment_schedule_slot_servicerequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="EncounterParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("practitioner_id", models.BigIntegerField(db_index=True)),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("ATND", "Attending Physician"),
                            ("PPRF", "Primary Performer"),
                            ("PART", "Participant"),
                            ("NURSE", "Assigned Nurse"),
                            ("CONS", "Consultant"),
                            ("REF", "Referring Physician"),
                        ],
                        default="PART",
                        max_length=10,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        db_column="encounter_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="care_team",
                        to="admission.encounter",
                    ),
                ),
            ],
            options={
                "db_table": "encounter_participant",
                "unique_together": {("encounter", "practitioner_id")},
            },
        ),
    ]
