# Generated by Django 6.0.4 on 2026-05-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleModuleConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("doctor", "Doctor"),
                            ("nurse", "Nurse"),
                            ("lab_technician", "Lab Technician"),
                            ("pharmacist", "Pharmacist"),
                            ("billing_clerk", "Billing Clerk"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("modules", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "role_module_config",
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="logo_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin"),
                    ("doctor", "Doctor"),
                    ("nurse", "Nurse"),
                    ("lab_technician", "Lab Technician"),
                    ("pharmacist", "Pharmacist"),
                    ("billing_clerk", "Billing Clerk"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
