# Generated by Django 6.0.4 on 2026-05-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_admin_role_logo_role_module_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="address_postal_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="physical_type_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="type_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="address_postal_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="contact_postal_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
