# Generated by Django 6.0.4 on 2026-05-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_fix_unique_constraints_org_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="altitude",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=18, null=True
            ),
        ),
    ]
