# Generated by Django 6.0.4 on 2026-05-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_location_coordinates_decimal"),
    ]

    operations = [
        migrations.AddField(
            model_name="practitioner",
            name="prc_license_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
