# Generated by Django 6.0.5 on 2026-05-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_phcore_alignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorFeeSchedule",
            fields=[
                ("fee_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "practitioner_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Links to accounts.Practitioner.practitioner_id (Fortress pattern)",
                        null=True,
                    ),
                ),
                (
                    "practitioner_name",
                    models.CharField(
                        blank=True,
                        help_text="Cached display name for the practitioner",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "specialty_code",
                    models.CharField(
                        blank=True,
                        help_text="SNOMED CT specialty code (e.g. 394814009 = General practice)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "specialty_display",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "consultation_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "professional_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "doctor_fee_schedule",
                "ordering": ["practitioner_name", "specialty_display"],
            },
        ),
        migrations.CreateModel(
            name="ProcedurePriceConfig",
            fields=[
                ("price_id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("surgical", "Surgical"),
                            ("diagnostic", "Diagnostic"),
                            ("therapeutic", "Therapeutic"),
                            ("rehabilitative", "Rehabilitative"),
                            ("preventive", "Preventive"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "procedure_price_config",
                "ordering": ["category", "code"],
            },
        ),
        migrations.CreateModel(
            name="RoomTypeDefinition",
            fields=[
                ("room_type_id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "daily_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "room_type_definition",
                "ordering": ["code"],
            },
        ),
    ]
