# Generated by Django 6.0.4 on 2026-05-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="total_currency",
            field=models.CharField(blank=True, default="PHP", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="claim",
            name="total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.CreateModel(
            name="Coverage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                ("coverage_id", models.AutoField(primary_key=True, serialize=False)),
                ("type_code", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "type_display",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "policy_holder_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "subscriber_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("beneficiary_id", models.BigIntegerField(db_index=True)),
                (
                    "payor_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "subscriber_pin",
                    models.CharField(
                        blank=True,
                        help_text="PhilHealth member PIN (XX-XXXXXXXXX-X format)",
                        max_length=14,
                        null=True,
                    ),
                ),
                ("class_code", models.CharField(blank=True, max_length=100, null=True)),
                ("class_name", models.CharField(blank=True, max_length=255, null=True)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("dependent", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "relationship_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "relationship_display",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("order", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("network", models.CharField(blank=True, max_length=255, null=True)),
                ("cost_to_beneficiary", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "billing_coverage",
                "indexes": [
                    models.Index(
                        fields=["beneficiary_id"], name="billing_cov_benefic_b9d354_idx"
                    ),
                    models.Index(
                        fields=["subscriber_pin"], name="billing_cov_subscri_5274bb_idx"
                    ),
                    models.Index(
                        fields=["status"], name="billing_cov_status_0da537_idx"
                    ),
                    models.Index(
                        fields=["payor_id"], name="billing_cov_payor_i_5ab5bc_idx"
                    ),
                ],
            },
        ),
    ]
