# Generated by Django 6.0.4 on 2026-05-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_add_coverage_fix_claim_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="coverage_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="claimresponse",
            name="payment_amount_currency",
            field=models.CharField(blank=True, default="PHP", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="claimresponse",
            name="payment_amount_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
